Support for Swift 5.9 toolchain & macOS Sonoma beta
swiftwasm/carton pull request #402
Opened 2023-08-06 00:07 UTC by furby-tm

This release adds SwiftWasm 5.9 toolchain support, which includes usability with macOS Sonoma beta.

```swift
- checking Swift compiler path: /Users/furby/.carton/sdk/wasm-5.9-SNAPSHOT-2023-08-01-a/usr/bin/swift
- checking Swift compiler path: /Users/furby/.swiftenv/versions/wasm-5.9-SNAPSHOT-2023-08-01-a/usr/bin/swift
- checking Swift compiler path: /Users/furby/Library/Developer/Toolchains/swift-wasm-5.9-SNAPSHOT-2023-08-01-a.xctoolchain/usr/bin/swift
Inferring basic settings...
- swift executable: /Users/furby/Library/Developer/Toolchains/swift-wasm-5.9-SNAPSHOT-2023-08-01-a.xctoolchain/usr/bin/swift
SwiftWasm Swift version 5.9-dev (LLVM 8250a14f5d3ef6a, Swift 57acd8f2a758d01)
Target: arm64-apple-darwin23.0.0

Parsing package manifest:
[debug]: evaluating manifest for 'cosmicportal' v. unknown- development binary to serve: /Users/furby/dev/Atmos/CosmicPortal/.build/wasm32-unknown-wasi/debug/CosmicPortal.wasm

Building the project before spinning up a server...
Compiling...
/Users/furby/Library/Developer/Toolchains/swift-wasm-5.9-SNAPSHOT-2023-08-01-a.xctoolchain/usr/bin/swift build -c debug --product CosmicPortal --triple wasm32-unknown-wasi -Xswiftc -Xclang-linker -Xswiftc -mexec-model=reactor -Xlinker --export=main -Xlinker /Users/furby/.carton/static/so_sanitizer.wasm -Xlinker --stack-first[0/1] Planning build
Building for debugging...
[0/1] Linking CosmicPortal.wasm
Build complete! (3.97s)

`swift` process finished successfully
`swift build` completed in 4.22 seconds
Binary transformation for Safari compatibility completed in 0.34 seconds
```

2023-08-15 21:25 UTC, STREGA commented on Package.swift
SwiftPM's package now requires Swift 5.7, please update Cartons's Package.swift to also require 5.7 tools.
And please update the deprecations that this change will cause for the dependencies.

2023-08-15 21:35 UTC, STREGA commented on Sources/CartonHelpers/DefaultToolchain.swift
> +public let defaultToolchainVersion = "wasm-5.9-SNAPSHOT-2023-08-01-a"
Please use 5.9-RELEASE for the toolchain version.
<sub>Even though it seems fine, we don't want to use a pre-release toolchain for a production carton release.</sub>

2023-08-15 21:51 UTC, STREGA requested changes
Thanks for taking to the time to make these changes and create a pull-request. 
It's appreciated!

I've got had few small changes needed when you get a chance.

Some of the changes involve using the Swift 5.9 release toolchain, even though it doesn't exist yet. The reason for that is because I want to avoid using snapshots for a major release of Carton. So I'm going to hold off merging this until 5.9 is released which should happen with Xcode 15's release in early September which isn't very far away.

2023-08-15 22:44 UTC, furby-tm commented on Package.swift
Require 5.7 tools to match SwiftPM.
This change includes updates to package deprecations.

2023-08-15 23:20 UTC, STREGA commented
Awesome! Don't forgot to use Swift 5.9 RELEASE in the Dockerfile as well.

2023-08-15 23:28 UTC, furby-tm commented
Good catch! I have also [bumped the docker base image](https://github.com/swiftwasm/carton/pull/402/commits/a586c737ae258b8921e5f75a4217a35d94f20724) pending 5.9's release, as well.

2023-08-16 00:05 UTC, STREGA approved these changes
Note: Deferring merge until Swift 5.9 is released. Checks are expected to fail until then.

2023-09-30 10:59 UTC, merged